version: "3.9"

services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src
  admin:
    command: npm run develop
    environment:
      NODE_ENV: development
      STRAPI_HOST: ${STRAPI_DEV_HOST}
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/configs/nginx.conf.dev:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_HOST=${DEV_NGINX_HOST}
      - STRAPI_HOST=${STRAPI_DEV_HOST}
